services:
  - type: web
    name: finly-python-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: PYTHON_ENV
        value: production
